version: '3.7'

networks:
  airoport:
    driver: bridge

services:
  mysql_database:
    image: mysql:8
    container_name: mysql_database
    restart: always
    ports:
      - '3306:3306' 
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mydb
      MYSQL_PASSWORD: admin
      MYSQL_USER: admin

    volumes:
      - ./docker/mysql:/var/lib/mysql/
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

    networks:
      - airoport


  django-app:
    build:
      context: .
      dockerfile: ./backend/dockerfile
    restart: always
    volumes:
      - ./backend/airoport_project/staticfiles:/home/django-app/staticfiles
      - ./backend/airoport_project/general.log:/home/django-app/general.log
    ports:
      - 8000:8000
    networks:
      - airoport

  nginx:
    build:
      context: . 
      dockerfile: ./nginx/dockerfile
    volumes:
      - ./backend/airoport_project/staticfiles:/home/app/static
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django-app
    restart: always
    ports:
      - 80:80
    networks:
      - airoport