FROM python:3.9-alpine

RUN mkdir - p /home/django-app

WORKDIR /home/django-app

#установка зависимостей
COPY ./backend/airoport_project .
RUN pip install --no-cache-dir -r ./requirements.txt

RUN ls -a

#запуск 
RUN chmod +x ./gunicorn_run.sh

RUN chmod +x ./general.log

ENTRYPOINT ["./gunicorn_run.sh"]

EXPOSE 8000