-- MySQL Script generated by MySQL Workbench
-- Tue Dec 24 22:14:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Авиакомпания`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Авиакомпания` (
  `Тариф` INT NULL,
  `Название авиакомпании` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Название авиакомпании`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Тариф`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Тариф` (
  `Название тарифа` VARCHAR(45) NOT NULL,
  `Допустимый вес багажа` DECIMAL(6,3) NULL,
  `Допустимый вес ручной клади` DECIMAL(6,3) NULL,
  `Доп.плата за питомца` BOOLEAN NULL,
  `Возможность изменения билета` BOOLEAN NULL,
  `Выбор места` BOOLEAN NULL,
  `Возможность возврата` BOOLEAN NULL,
  `Кол-во начисления бонусов` INT NULL,
  `Возможность повышения класса` BOOLEAN NULL,
  `Наличие открытой даты вылета` BOOLEAN NULL,
  `Приоритетная регистрация` BOOLEAN NULL,
  `Приоритетный досмотр` BOOLEAN NULL,
  `Приоритетная посадка` BOOLEAN NULL,
  `Приоритетное обслуживание багажа` BOOLEAN NULL,
  `Код тарифа` VARCHAR(45) NOT NULL,
  `Авиакомпания_Название авиакомпании` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Код тарифа`),
  INDEX `fk_Тариф_Авиакомпания1_idx` (`Авиакомпания_Название авиакомпании` ASC) VISIBLE,
  CONSTRAINT `fk_Тариф_Авиакомпания1`
    FOREIGN KEY (`Авиакомпания_Название авиакомпании`)
    REFERENCES `mydb`.`Авиакомпания` (`Название авиакомпании`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Билет`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Билет` (
  `Номер полета` VARCHAR(45) NOT NULL,
  `Класс` VARCHAR(45) NOT NULL,
  `Ндд` DATE NOT NULL,
  `Ндп` DATE NOT NULL,
  `Наличие багажа` BOOLEAN NULL,
  `Наличие ручной клади` BOOLEAN NULL,
  `Наличие питомца` BOOLEAN NULL,
  `Номер билета` VARCHAR(45) NOT NULL,
  `Цена билета` DECIMAL(19,2) NOT NULL,
  `Тариф_Код тарифа` VARCHAR(45) NULL,
  `Выкуплены` BOOLEAN NOT NULL DEFAULT false,
  PRIMARY KEY (`Номер билета`),
  INDEX `fk_Билет_Тариф_idx` (`Тариф_Код тарифа` ASC) VISIBLE,
  INDEX `fk_Номер_полета_idx` (`Номер полета` ASC) VISIBLE, 
  CONSTRAINT `fk_Билет_Тариф`
    FOREIGN KEY (`Тариф_Код тарифа`)
    REFERENCES `mydb`.`Тариф` (`Код тарифа`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

  CONSTRAINT `fk_Номер_полета`
    FOREIGN KEY(`Номер полета`)
    REFERENCES `mydb`.`Полет` (`Номер рейса`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Кассир`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Кассир` (
  `Номер кассира` INT NOT NULL AUTO_INCREMENT,
  `Фамилия` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Номер кассира`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Виза`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Виза` (
  `Срок действия` INT NULL,
  `Тип визы` VARCHAR(45) NULL,
  `Кол-во разрешенных въездов` INT NULL,
  `Номер визы` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Номер визы`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Полет`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Полет` (
  `Место отправления` VARCHAR(45) NOT NULL,
  `Место назначения` VARCHAR(45) NOT NULL,
  `Дата вылета` DATE NOT NULL,
  `Время вылета` TIME NOT NULL,
  `Кол-во пассажиров` INT NULL,
  `Международный` BOOLEAN NOT NULL,
  `Номер рейса` VARCHAR(45) NOT NULL,
  `Рейс отменен` BOOLEAN NOT NULL DEFAULT FALSE,
  `Авиакомпания_Название авиакомпании` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Номер рейса`),
  INDEX `fk_Полет_Авиакомпания1_idx` (`Авиакомпания_Название авиакомпании` ASC) VISIBLE,
  CONSTRAINT `fk_Полет_Авиакомпания1`
    FOREIGN KEY (`Авиакомпания_Название авиакомпании`)
    REFERENCES `mydb`.`Авиакомпания` (`Название авиакомпании`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Пассажир`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Пассажир` (
  `Фамилия` VARCHAR(128) NOT NULL,
  `Имя` VARCHAR(128) NOT NULL,
  `Отчество` VARCHAR(128) NULL,
  `Номер телефона` VARCHAR(45) NULL,
  `Возраст` INT NULL,
  `Серия` VARCHAR(45) NOT NULL,
  `Номер` VARCHAR(45) NOT NULL,
  `Серия загран паспорта` VARCHAR(45) NULL UNIQUE,
  `Номер загран паспорта` VARCHAR(45) NULL UNIQUE,
  PRIMARY KEY (`Серия`, `Номер`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Покупка`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Покупка` (
  `Финальная цена` DECIMAL(19,2) NOT NULL,
  `Дата заказа` DATE NOT NULL,
  `Время заказа` TIME NOT NULL,
  `Номер заказа` VARCHAR(45) NOT NULL,
  `Кассир_Номер кассира` INT NOT NULL,
  `Виза_Номер визы` VARCHAR(45) NULL,
  `Полет_Номер рейса` VARCHAR(45) NOT NULL,
  `Билет_Номер билета` VARCHAR(45) NOT NULL,
  `Пассажир_Серия` VARCHAR(45) NOT NULL,
  `Пассажир_Номер` VARCHAR(45) NOT NULL,
  `Статус покупкки` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Номер заказа`),
  INDEX `fk_Покупка_Кассир1_idx` (`Кассир_Номер кассира` ASC) VISIBLE,
  INDEX `fk_Покупка_Виза1_idx` (`Виза_Номер визы` ASC) VISIBLE,
  INDEX `fk_Покупка_Полет1_idx` (`Полет_Номер рейса` ASC) VISIBLE,
  INDEX `fk_Покупка_Билет1_idx` (`Билет_Номер билета` ASC) VISIBLE,
  INDEX `fk_Покупка_Пассажир1_idx` (`Пассажир_Серия` ASC, `Пассажир_Номер` ASC) VISIBLE,
  CONSTRAINT `fk_Покупка_Кассир1`
    FOREIGN KEY (`Кассир_Номер кассира`)
    REFERENCES `mydb`.`Кассир` (`Номер кассира`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Покупка_Виза1`
    FOREIGN KEY (`Виза_Номер визы`)
    REFERENCES `mydb`.`Виза` (`Номер визы`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Покупка_Полет1`
    FOREIGN KEY (`Полет_Номер рейса`)
    REFERENCES `mydb`.`Полет` (`Номер рейса`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Покупка_Билет1`
    FOREIGN KEY (`Билет_Номер билета`)
    REFERENCES `mydb`.`Билет` (`Номер билета`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Покупка_Пассажир1`
    FOREIGN KEY (`Пассажир_Серия` , `Пассажир_Номер`)
    REFERENCES `mydb`.`Пассажир` (`Серия` , `Номер`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
